* -----------------------------------------------------*
*              BEAVRS PWR MODEL                        *
* -----------------------------------------------------*


***** Configurations with burnable poisons
***** Details from RELEASE rev. 3.0
***** Source of info indicated by [page number] in comments


***** STANDARD MECHANICAL DESIGN SPECIFIC *********
PIN 4  0.56134   0.60198 /  'MOD'    'BOX'  * GUIDE TUBE [90-91]
PIN 4 0.21400 0.23051 0.24130 0.42672 0.43688 0.48387 0.56134 0.60198 /
        'AIR' 'CRS' 'AIR' 'BP1' 'AIR' 'CRS' 'MOD' 'BOX'
        // 1 'PYR' 'ROD' *BP [9]
SPA 19.187,,, 6.55 / 304=100.00  * SPACER [13] * 6 Zr spacers in active core
****************************************************
