* -----------------------------------------------------*
*              BEAVRS PWR MODEL                        *
* -----------------------------------------------------*


***** General details of operating design
***** Details from RELEASE rev. 3.0
***** Source of info indicated by [page number] in comments

************ INVARIANT DATA **************
PDE 104.5 'KWL' * power density [3]
PRE 155.13      * pressure [3]
TFU 900         * approximate fuel temperature
TMO 586.5       * average moderator temperature in Kelvin, set to inlet+20 [63]
BOR 600.00      * average boron
PWR 17 1.26 21.50    * geometric parameters [13]
CAN 6.55/304=100.0   * CLADDING
BOX 6.55/304=100.0   * BOX WALL
CRS 7.90/347=100.0   * CONTROL ROD - SS
PIN 1  0.39218   0.40005   0.45720 * FUEL PIN [84-86]
PIN 2  0.56134   0.60198 /  'MOD'    'BOX'  * INSTR TUBE [90-91]
PIN 3  0.56134   0.60198 /  'MOD'    'BOX'  * GUIDE TUBE [90-91]
******************************************
