* -----------------------------------------------------*
*              BEAVRS PWR MODEL                        *
* -----------------------------------------------------*

***** Configurations without burnable poisons
***** Details from RELEASE rev. 3.0
***** Source of info indicated by [page number] in comments

***** STANDARD MECHANICAL DESIGN SPECIFIC *********
PIN 3  0.48387  0.56134   0.60198  /
        'CRS'   'MOD'   'BOX'
        // 1  'CR1' 'ROD'                * CONTROL ROD STAINLESS STEEL GEOMETRY [11]
PIN 3  0.38227 0.38608  0.48387  0.56134   0.60198  /
        'AIC'  'AIR' 'CRS'   'MOD'   'BOX'
        // 1  'CR2' 'ROD'                * CONTROL ROD LOWER GEOMETRY [11]
PIN 3  0.37338 0.38608  0.48387  0.56134   0.60198  /
        'B4C'  'AIR' 'CRS'   'MOD'   'BOX'
        // 1  'CR3' 'ROD'                * CONTROL ROD UPPER GEOMETRY [11]

SPA 19.187,,, 6.55 / 304=100.00  * SPACER [13] * 6 Zr spacers in active core
****************************************************
